name: one_second_diary
description: Record one second of your day, everyday.

publish_to: "none"

version: 1.5.0+9

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  about: ^2.1.1
  avatar_glow: ^2.0.2
  camera: 
    git:
      url: https://github.com/KyleKun/plugins.git
      path: packages/camera/camera
      ref: fix_fail_get_dimensions_on_profile
  device_info_plus: ^8.0.0
  ffmpeg_kit_flutter_full_gpl: ^5.1.0
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.1
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^12.0.4
  fluttertoast: ^8.1.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  group_radio_button: ^1.3.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  introduction_screen: ^3.1.1
  native_device_orientation: ^1.1.4
  open_file:
    git:
      url: https://github.com/KyleKun/open_file.git
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  rive: ^0.9.1
  saf: ^1.0.3+4
  salomon_bottom_bar: ^3.3.1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  timer_builder: ^2.0.0
  timezone: ^0.9.0
  url_launcher: ^6.1.7
  video_player: ^2.4.9
  video_thumbnail: ^0.5.3
  video_trimmer:
    git:
      url: https://github.com/KyleKun/video_trimmer.git
      ref: main
  wakelock: ^0.6.2
  logger: ^1.1.0
  stack_trace: ^1.10.0
  flutter_archive: ^5.0.0
  flutter_email_sender: ^5.2.0
  synchronized: ^3.0.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - CHANGELOG.md
    - CONTRIBUTORS.md

  fonts:
    - family: Magic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
