name: one_second_diary
description: Record one second of your day, everyday.

publish_to: "none"

version: 1.5.2+15

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  about: ^2.1.3
  avatar_glow: ^2.0.2
  camera: ^0.10.5+3
  device_info_plus: ^9.0.3
  ffmpeg_kit_flutter_full_gpl: ^5.1.0
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.2
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^15.1.1
  fluttertoast: ^8.2.2
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  get: ^4.6.6
  group_radio_button: ^1.3.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  introduction_screen: ^3.1.11
  native_device_orientation: ^1.1.4
  path_provider: ^2.1.0
  permission_handler: ^10.4.5
  rive: ^0.11.14
  salomon_bottom_bar: ^3.3.2
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  timer_builder: ^2.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.12
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3
  video_trimmer:
    git:
      url: https://github.com/KyleKun/video_trimmer.git
      ref: main
  wakelock_plus: ^1.1.1
  logger: ^2.0.1
  stack_trace: ^1.10.1
  flutter_archive: ^5.0.0
  flutter_email_sender: ^6.0.1
  synchronized: ^3.1.0
  open_filex: ^4.3.2
  media_store_plus:
    git:
      url: https://github.com/KyleKun/media_store_plus.git
      ref: main
  wechat_assets_picker:
    git:
      url: https://github.com/KyleKun/flutter_wechat_assets_picker.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - CHANGELOG.md
    - CONTRIBUTORS.md

  fonts:
    - family: Magic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
