name: one_second_diary
description: Record one second of your day, everyday.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get:
  camera:
  path_provider:
  better_player:
  rflutter_alert:
  hive:
  flutter_ffmpeg: ^0.3.1
  permission_handler:
  tapioca:
  gallery_saver:
  salomon_bottom_bar:
  video_editor:
  introduction_screen:
  flip_card:
  avatar_glow:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Magic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
